---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: graylog2-latest
    run_list:
      - recipe[graylog2::default]
    attributes:
      graylog2:
        version: "0.20.6"
