---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5
  - name: centos-7.1

suites:
  - name: graylog2-latest
    run_list:
      - recipe[graylog2::default]
    attributes:
      graylog2:
        version_minor: "1.2"
